### ISSUE TITLE
Transport augeas test failed

### ISSUE THREAD

**Issue by dogjarek** [camptocamp/puppet-postfix#241]
Trying to implement this:
hiera data:
```
postfix_transport:
  "*":
    destination: "smtp"
    nexthop: "[myhostname]:587"
```
manifest:
```  create_resources(postfix::transport, $postfix_transport) ```

drops validation error as it doesn't recognise `[myhostname]` and port straight after.

`myhostname` without `[]` works fine.
